# Generated by Django 2.2.2 on 2019-06-07 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('long_position', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat_position', models.DecimalField(decimal_places=3, max_digits=8)),
                ('rating', models.CharField(choices=[('One', 'One : Anomaly'), ('Two', 'Two : Incident '), ('Three', 'Disaster with Local Consequences'), ('Four', 'State of Local Emergency'), ('Five', 'State of Emergency')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField(default=0)),
                ('occupation', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=70)),
                ('address', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=50)),
                ('address_province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], max_length=2)),
                ('address_country', models.CharField(default='Canada', max_length=50)),
                ('last_verified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('time_assigned', models.DateTimeField(auto_now_add=True)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('long_position', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat_position', models.DecimalField(decimal_places=3, max_digits=8)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Emergency')),
                ('person_assigned', models.ManyToManyField(to='people.Person')),
                ('skill_needed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(to='people.Skill'),
        ),
    ]
